"""Advisory GenAI Security Analyst abstractions.

Architectural Rule:
The GenAI Security Analyst is strictly advisory. It must explain and investigate
evidence generated by the detection system; it must NOT be the authoritative source
for threat classification.

Full implementation belongs to Phase 8 (GenAI Security Analyst).
"""

from abc import ABC, abstractmethod
from typing import Dict, Optional
from sentinel_models.alerts import Alert


class BaseAnalystAgent(ABC):
    """Abstract interface for advisory LLM security analysis."""

    @abstractmethod
    def explain_incident(self, alert: Alert) -> str:
        """Generate a natural-language technical explanation of the alert evidence."""
        raise NotImplementedError("GenAI analyst explanation will be implemented in Phase 8.")

    @abstractmethod
    def generate_playbook(self, alert: Alert) -> str:
        """Generate an advisory remediation playbook for human SOC review."""
        raise NotImplementedError("Playbook generation will be implemented in Phase 8.")
