"""Advisory GenAI Security Analyst abstractions.

Architectural Rule:
The GenAI Security Analyst is strictly advisory. It must explain and investigate
evidence generated by the detection system; it must NOT be an inline prevention,
autonomous execution, or primary threat classification engine.
"""

from abc import ABC, abstractmethod
from typing import Any, Dict, List, Optional
from sentinel_models.alerts import Alert, SecurityAlert
from sentinel_models.ai_analyst import AlertAnalysisReport, AnalystQuestionResponse


class BaseAnalystAgent(ABC):
    """Abstract interface for advisory LLM security analysis."""

    @abstractmethod
    async def analyze_alert(
        self,
        alert: SecurityAlert,
        flows: Optional[List[Any]] = None,
        mode: str = "comprehensive",
    ) -> AlertAnalysisReport:
        """Generate a grounded advisory incident report for the specified alert."""
        pass

    @abstractmethod
    async def ask_question(
        self,
        alert: SecurityAlert,
        question: str,
        conversation_history: Optional[List[Dict[str, str]]] = None,
    ) -> AnalystQuestionResponse:
        """Answer an analyst inquiry grounded strictly in the alert context."""
        pass

    def explain_incident(self, alert: Alert) -> str:
        """Backward-compatible synchronous helper."""
        return alert.explanation

    def generate_playbook(self, alert: Alert) -> str:
        """Backward-compatible advisory checklist generator."""
        return f"Investigation checklist for {alert.threat_class}: Review flow telemetry and endpoint logs."
